[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0:5060

; If Android clients connect from another subnet/NAT, set these to the PBX LAN
; or public address as appropriate.
; external_media_address = 10.10.20.157
; external_signaling_address = 10.10.20.157
; local_net = 10.10.20.0/24
